language: ruby
rvm: 2.2.0
notifications:
  email: false
script: xvfb-run rake test:all
services: mongodb
env:
  global:
  - DISPLAY=:99.0
  - RACK_ENV=testing
  - secure: W3b+AlBvaVvue04mNOuNYOHb9gJ+QL73Og9rEShG5oax1Rl+tQBrSFgCGdE5zPQBgGl4MXVg64mSSK8W8vgMbYCHmkcJcR/35vZAx2LHuVwyOJhnqyzkAYhNVxprf6AFOnvwP6e6ff/bkBquGFXjnIIPrPjj/Z5JFIOwqvEMwC4=
  - secure: A2yzFdeU/LvkhK1E/0J6+eJ3us2KEBWHP57ua8/t6/g5ZBVNWQ/CEgiQ+e/Iy/A6qvXoMaG+9CHTHzu/xLLOzwWighBHAXUF8RoRnYDylsdtsuiXgfia5CpdvlMIm6lprk5jnYm8RqN0lyyLiszLyftkaixXHhTrk4tYROctPxs=
  - secure: h1/seAKNUbsGik8+h1yiN4X/TRnL/gepz8gnO3wd/Hv6+xygbYxflJ8VDjx82kBO84cL5cO3Pxnjqss4v8ah5z6IuhcHGBIU64M7AuHaD8be2GE+xwstC+7I/tjb1LkW9odkSE2499NyCQ4xxGqMzkLtJmFsOwRl3WmTsPbsKGk=
  - secure: jBHBgwltBLWIXeTt8T4k779dO75Isofy/33qVUnnjVBXm4sV/fMzE3w+GIxMxkelSF/GeOFtPhSm92SN4Lts9BRhWqkm53jKEj3+3HlxBtxm9YDo2ypBqhXNKafeSNrrbY341KnsD/6HM/eb2vAV8IwoUTFEqi3F9BQglwIN/U8=
  - secure: Ry3P7GF+/64RGee0yRF/Wkq9Mv9NiNFlHtGluKAEyEZrq6LUO8sG3p7Lv6mPcYNKW37SP3naWc/Jg7Y41Fa74JSWDk6y1mr0ZAHSVmFP+weyOtvdR6vyUTC5/yVe2DRP98uCWnCBx/6loI/DDM5Z4NeMW/Ye5qp/5g4IsSsadqk=
before_install:
- sh -c 'if [ -n "$QMAKE" ]; then sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  && sudo apt-get update && sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev;
  fi'
install: bundle
