sudo: false
language: ruby
rvm: 2.2.0
notifications:
  email: false
script: xvfb-run rake test:all
services: mongodb
cache: bundler
env:
  global:
  - DISPLAY=:99.0
  - RACK_ENV=test
install:
- npm install testem -g
- bundle
