sudo: false
language: ruby
rvm: 2.2.0
notifications:
  email: false
script: xvfb-run rake test:all
services: mongodb
cache: bundler
env:
  global:
  - DISPLAY=:99.0
  - RACK_ENV=test
  - secure: byekKEwdF+4kurrSkAbRm5rtKlP32Uw2ZKv2bFrewZ7lXx+N87ysijs3/Cmy4twsyzpTXAwsqDPS2zfn9rfVbwGLLmrY/IJFgAgY2CMjO2bCDBcDcloezpHvpqqBO7fVGee9DUJ7nr1QdARfVbbtkHvsGoAc2M3HX71EAphMcIo=
  - secure: IOhxVfITF6H0+7vTHqDtdtTkZPfMLps/yCfXdqNJxrNcvWT9c/h28k3CzBD0+GsbTCoO9ijrtQJn9gkWeweTtV5LgPeZhecyPFc9hQoomYePM3r7KfSk90aJhPnG8RMJsQvyRdhzjfXczphb8tPf+oa7NCq+VBIi11X4YyONgtY=
  - secure: Cn+2rFDDANJN/KpWBnxPOX3Ser1Oy7vi7s9ykuDejLI4gwosmktPzFIMrR85426fNyaGI6jRIev86Amdp5UvKzhahL7GDEUvwSD68O29L/RSLn42cjrf0u/NMNu9eXFUB/cHPy3rkoqOee6uJyoH+ZhD0fuYH6ojSBxjPiB1ej0=
  - secure: XEr0CJhoW+9v9KcQqfoK/igdqLJtAblz3eGECD7G4RYNPOeLZsOImv03rs+zRUi40gd4iqxSkcX1F4/NmOxWhmGqXy3f3u4/HFAWneMjQm0j4NzQSVFvaLMJx2vURdUsDeJYWVt57xm7ow4Kg02xlOpDFmKLRdn5/SaG8iN/sGg=
  - secure: d1eEQH6CsyEitrJwmfK5bzDVoKa3ZWskaLxKrRlcUdVzyDReaBb2RhhPFkNmJnOmcQYSHfEIqmon7GDS/Uf375VL9zRpcTh08hRb+UQIj/Wr1PUsPEO0TytIA6bA9Kudp5TPx3Ky77uW64OY4y/Ihae4rH193JVobNgtJcdrNUw=
  - secure: gIYwEOTgmCsDuzs/23IMkx7zAq/gXIHREf+c0EQ8FCEjUJjfa5Iwtrzi6U+ylwXspXHBx3Cslt1NYNcL25r29f9RAA73tONVyxevilae5bdytZzgt1i3Y5lPEPNWX28U8JdDqyyvt6AJnaOkDt8Jbsmj9R8HJOuVXSJeZb4lDjI=
  - secure: k3gSQaWUFqZwpiRHkUs30XBIAg/AJoWIGxLJnNOmJN30MpnP4BoO0aCv/yOS1XOePi741iPzbS56EkwZFPEppL+f3s+m4063+b/ff9AL5ykY1zePxSp+W7hLIRfO9dF8xsnWOKGixjgrEByXd4FaJpQKO5mG61uJD45Ay3Y1dX8=
install:
- npm install testem -g
- bundle
