language: ruby
rvm: 2.2.0
notifications:
  email: false
script: xvfb-run rake test:all
services: mongodb
env:
  global:
  - DISPLAY=:99.0
  - RACK_ENV=testing
  - secure: ixpYdEHOqIRhGMs7ah8zAtLqZymV6Ywb+7nMl6G5W5lANNa+63JV+OX0lHygJXWMmwcYBqEcMRdhHA/d0+h5zSUv/nIYCBDPxFOp5ehKzUe3VaYluw9WJP/uIaKEOV1LiihAszDAp+5iWxww1hs6bBgt1TM8KzJGey7G4I4JtEs=
  - secure: VbFWkwZogerrHvlFCcRV3a30X7Qix9XGuYs8W6AmeB8REF+szIEuVcZzFAEWbIydLutUSQRG9yt1rV5cozBBa51BiPV8kwPx4g/6HCpfAdvTdMcmWYEi8jXRwpIYnKFqtQyE3w1cJdRSrkcN2PithocTyeupWnHnIorGAKdl730=
  - secure: Y2xnuDUJXY+PUWPwpx3iU3gIrlUoDge0tKwl5/fSN5WG9ui/7IZry3u329OKi+3gkJyPAvxSyTsOEFj1nmJGX136bnzVPjyQvMyoHBoqMKIqQCJe2QKNd30MlSYh6hQBWUFrCYPXXfO0AeqeLk9WwzGlyp6LwQoKpBYO2Fgiz+E=
  - secure: ZLoI6FSLI5mIZbru83kkEvpBSeoU1zL1doTy0SYVFy0v/A8ROGgbv4Gw9lZANTgIvWDjbPBSRrf6YU+Vrdh/ytaVg98ZospClbb2hXk40y8jSrbdC/4Xg77qIxuAdiYWjUSHeCKg8qCNCleK8goEPqHr79Y/HJGUGcQEdwXN8fQ=
  - secure: Nqv89hEUOfTuqlQu9xISjktwPMooUAK/nSmyEd5oCjVlE2n7gUbxb5HR5ZhDP2ieu5ro6QIXj9inbYUi6tdZo8Y2QcMP9bnnChr7z4Erx5IqvRSC5CuMFPd8llWUK5Fv56+KqXG8NBSQy40WYGUHiUIuWwlh8hyZQ1A4gjJRC7U=
before_install:
- sh -c 'if [ -n "$QMAKE" ]; then sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  && sudo apt-get update && sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev;
  fi'
install: bundle
